name: 'commit-test'
on: [push]
jobs:
  basic-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checksout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - run: npm test
