on:
  pull_request:
    branches:
      # run scripts/make-release to create a release. it handles the versioning,
      # creating the branch, and pushing it to github to trigger this workflow.
      - main
      - master
    types:
      - closed

jobs:
  release-to-npm:
    # run this when the PR is merged, but it runs on the PR branch, not the target
    # branch it's merged into.
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/')

    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - uses: actions/setup-node@v3
          with:
            node-version: 18
        - run: npm install
        - id: publish
          uses: JS-DevTools/npm-publish@v3
          with:
            dry-run: false
            token: ${{ secrets.NPM_TOKEN }}
            access: public
